apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
  namespace: app
type: Opaque
stringData:
  AWS_REGION: "ap-southeast-1"
  DYNAMODB_PRODUCTS_TABLE: "products_table"
  DAX_ENDPOINT: "REPLACE_DAX_ENDPOINT"
  S3_BUCKET: "REPLACE_S3_BUCKET"
