apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: app
type: Opaque
stringData:
  AWS_REGION: "ap-southeast-1"
  DYNAMODB_ORDERS_TABLE: "orders_table"
  SQS_QUEUE_URL: "REPLACE_SQS_QUEUE_URL"
