apiVersion: v1
kind: Service
metadata:
  name: provider-service
  namespace: app
  labels:
    app: provider-service
spec:
  type: ClusterIP
  selector:
    app: provider-service
  ports:
    - name: http
      port: 80
      targetPort: 3002
      protocol: TCP
